// src/components/DisclaimerPage.tsx
import React from 'react';
import { X, AlertTriangle, FileText, Shield, Scale, Info } from 'lucide-react';

interface DisclaimerPageProps {
  isOpen: boolean;
  onClose: () => void;
}

export function DisclaimerPage({ isOpen, onClose }: DisclaimerPageProps) {
  if (!isOpen) return null;

  return (
    <div 
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fade-in"
      onClick={onClose}
    >
      <div 
        className="relative w-full max-w-4xl bg-[#0A0A0A] border border-[#2A2A2A] rounded-2xl shadow-2xl flex flex-col max-h-[90vh] animate-fade-in-up"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-[#2A2A2A] bg-gradient-to-r from-red-500/10 to-orange-500/10">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-xl bg-red-500/20 flex items-center justify-center border border-red-500/30">
              <AlertTriangle className="w-6 h-6 text-red-400" />
            </div>
            <div>
              <h2 className="text-2xl font-bold text-white font-mono">DISCLAIMER</h2>
              <p className="text-sm text-gray-400 font-mono">AI-Generated Content Notice</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-lg hover:bg-white/10 transition-colors"
            title="Close"
          >
            <X className="w-5 h-5 text-gray-400 hover:text-white" />
          </button>
        </div>

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-8 font-mono text-sm leading-relaxed">
          {/* Warning Banner */}
          <div className="mb-8 p-6 bg-red-500/10 border-2 border-red-500/30 rounded-xl">
            <div className="flex items-start gap-4">
              <AlertTriangle className="w-8 h-8 text-red-400 shrink-0 mt-1" />
              <div>
                <h3 className="text-lg font-bold text-red-400 mb-2">IMPORTANT NOTICE</h3>
                <p className="text-gray-300 leading-relaxed">
                  This application generates books using artificial intelligence. All content 
                  is AI-generated and may contain inaccuracies, outdated information, or 
                  factual errors. Users must independently verify all information before use.
                </p>
              </div>
            </div>
          </div>

          {/* Section 1: AI-Generated Content */}
          <section className="mb-8">
            <div className="flex items-center gap-3 mb-4">
              <FileText className="w-5 h-5 text-orange-400" />
              <h3 className="text-xl font-bold text-white">1. AI-Generated Content Notice</h3>
            </div>
            <div className="pl-8 space-y-4 text-gray-300">
              <p>
                <span className="text-orange-400 font-bold">[1.1]</span> All books, chapters, 
                and content produced by Pustakam Injin are entirely generated by artificial 
                intelligence language models.
              </p>
              <p>
                <span className="text-orange-400 font-bold">[1.2]</span> The AI may produce 
                content that appears accurate but contains factual errors, logical 
                inconsistencies, or outdated information (commonly known as "AI hallucinations").
              </p>
              <p>
                <span className="text-orange-400 font-bold">[1.3]</span> Content should be 
                treated as a <span className="text-yellow-400 font-semibold">starting point 
                for research</span>, not as a definitive or authoritative source.
              </p>
              <p>
                <span className="text-orange-400 font-bold">[1.4]</span> The application uses 
                multiple AI providers (Google Gemini, Mistral AI, ZhipuAI) - quality and 
                accuracy may vary between models and sessions.
              </p>
            </div>
          </section>

          {/* Section 2: Limitations */}
          <section className="mb-8">
            <div className="flex items-center gap-3 mb-4">
              <Info className="w-5 h-5 text-purple-400" />
              <h3 className="text-xl font-bold text-white">2. Known Limitations</h3>
            </div>
            <div className="pl-8 space-y-4 text-gray-300">
              <div className="space-y-2">
                <p className="text-purple-400 font-bold">⚠️ Factual Accuracy:</p>
                <p className="pl-6">
                  AI models may generate plausible-sounding but incorrect information, 
                  including fake citations, non-existent studies, or fabricated statistics.
                </p>
              </div>
              <div className="space-y-2">
                <p className="text-purple-400 font-bold">⚠️ Temporal Context:</p>
                <p className="pl-6">
                  AI models have knowledge cutoffs (typically early 2024-2025). Information 
                  about recent events, discoveries, or updates may be missing or incorrect.
                </p>
              </div>
              <div className="space-y-2">
                <p className="text-purple-400 font-bold">⚠️ Bias & Perspective:</p>
                <p className="pl-6">
                  AI models may reflect biases present in their training data, potentially 
                  affecting the tone, perspective, or cultural sensitivity of generated content.
                </p>
              </div>
              <div className="space-y-2">
                <p className="text-purple-400 font-bold">⚠️ Specialized Domains:</p>
                <p className="pl-6">
                  Content in highly technical, medical, legal, or specialized fields may 
                  lack the nuance and precision required for professional use.
                </p>
              </div>
            </div>
          </section>

          {/* Section 3: User Responsibilities */}
          <section className="mb-8">
            <div className="flex items-center gap-3 mb-4">
              <Shield className="w-5 h-5 text-green-400" />
              <h3 className="text-xl font-bold text-white">3. User Responsibilities</h3>
            </div>
            <div className="pl-8 space-y-4 text-gray-300">
              <p>
                <span className="text-green-400 font-bold">[3.1]</span> Users are 
                <span className="text-yellow-400 font-semibold"> solely responsible</span> for 
                verifying the accuracy of all AI-generated content before use.
              </p>
              <p>
                <span className="text-green-400 font-bold">[3.2]</span> Content must be 
                independently fact-checked and cross-referenced with authoritative sources 
                before being used for:
              </p>
              <ul className="pl-10 space-y-2 list-disc list-outside">
                <li>Academic citations or research</li>
                <li>Professional or commercial purposes</li>
                <li>Medical, legal, or financial decisions</li>
                <li>Educational materials for distribution</li>
                <li>Any context where accuracy is critical</li>
              </ul>
              <p>
                <span className="text-green-400 font-bold">[3.3]</span> Users assume 
                <span className="text-red-400 font-semibold"> full liability</span> for 
                how they use, interpret, publish, or distribute AI-generated content.
              </p>
            </div>
          </section>

          {/* Section 4: No Professional Advice */}
          <section className="mb-8">
            <div className="flex items-center gap-3 mb-4">
              <Scale className="w-5 h-5 text-orange-400" />
              <h3 className="text-xl font-bold text-white">4. Not Professional Advice</h3>
            </div>
            <div className="pl-8 space-y-4 text-gray-300">
              <p>
                <span className="text-orange-400 font-bold">[4.1]</span> Content generated by 
                Pustakam Injin is <span className="text-red-400 font-semibold">NOT</span> a 
                substitute for professional advice in:
              </p>
              <ul className="pl-10 space-y-2 list-disc list-outside">
                <li><span className="text-red-400">Medical & Healthcare</span> - Do not use for diagnosis, treatment, or health decisions</li>
                <li><span className="text-red-400">Legal Matters</span> - Do not use as legal counsel or for legal proceedings</li>
                <li><span className="text-red-400">Financial Planning</span> - Do not use for investment, tax, or financial advice</li>
                <li><span className="text-red-400">Safety & Engineering</span> - Do not use for critical safety or technical specifications</li>
                <li><span className="text-red-400">Academic Work</span> - Do not submit as original work without proper attribution</li>
              </ul>
              <p>
                <span className="text-orange-400 font-bold">[4.2]</span> Always consult 
                qualified professionals in the relevant field for specialized advice.
              </p>
            </div>
          </section>

          {/* Section 5: Intellectual Property */}
          <section className="mb-8">
            <div className="flex items-center gap-3 mb-4">
              <FileText className="w-5 h-5 text-cyan-400" />
              <h3 className="text-xl font-bold text-white">5. Intellectual Property</h3>
            </div>
            <div className="pl-8 space-y-4 text-gray-300">
              <p>
                <span className="text-cyan-400 font-bold">[5.1]</span> AI-generated content 
                may inadvertently replicate patterns, phrases, or structures from copyrighted 
                works in the AI's training data.
              </p>
              <p>
                <span className="text-cyan-400 font-bold">[5.2]</span> Users are responsible 
                for ensuring their use of generated content complies with applicable copyright 
                and intellectual property laws.
              </p>
              <p>
                <span className="text-cyan-400 font-bold">[5.3]</span> Pustakam Injin makes no 
                warranties regarding the originality or copyright status of generated content.
              </p>
            </div>
          </section>

          {/* Section 6: Warranty Disclaimer */}
          <section className="mb-8">
            <div className="flex items-center gap-3 mb-4">
              <AlertTriangle className="w-5 h-5 text-red-400" />
              <h3 className="text-xl font-bold text-white">6. Warranty Disclaimer</h3>
            </div>
            <div className="pl-8 space-y-4 text-gray-300">
              <p className="uppercase font-bold text-red-400">
                THIS SOFTWARE AND ALL GENERATED CONTENT ARE PROVIDED "AS-IS" WITHOUT WARRANTY 
                OF ANY KIND, EITHER EXPRESS OR IMPLIED.
              </p>
              <p>
                <span className="text-red-400 font-bold">[6.1]</span> Pustakam Injin makes 
                <span className="text-red-400 font-semibold"> NO WARRANTIES</span> regarding:
              </p>
              <ul className="pl-10 space-y-2 list-disc list-outside">
                <li>Accuracy, completeness, or reliability of generated content</li>
                <li>Fitness for any particular purpose</li>
                <li>Non-infringement of third-party rights</li>
                <li>Uninterrupted or error-free operation</li>
              </ul>
              <p>
                <span className="text-red-400 font-bold">[6.2]</span> In no event shall the 
                developers, contributors, or affiliated parties be liable for any damages 
                arising from use of this software or its generated content.
              </p>
            </div>
          </section>

          {/* Section 7: Data Privacy */}
          <section className="mb-8">
            <div className="flex items-center gap-3 mb-4">
              <Shield className="w-5 h-5 text-indigo-400" />
              <h3 className="text-xl font-bold text-white">7. Data Privacy & API Usage</h3>
            </div>
            <div className="pl-8 space-y-4 text-gray-300">
              <p>
                <span className="text-indigo-400 font-bold">[7.1]</span> All data is stored 
                locally in your browser. Pustakam Injin does not collect or store user data 
                on external servers.
              </p>
              <p>
                <span className="text-indigo-400 font-bold">[7.2]</span> Your content is sent 
                to third-party AI providers (Google, Mistral, ZhipuAI) for processing. Review 
                each provider's privacy policy:
              </p>
              <ul className="pl-10 space-y-2 list-disc list-outside text-orange-400">
                <li><a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="underline hover:text-orange-300">Google AI Privacy Policy</a></li>
                <li><a href="https://mistral.ai/terms/" target="_blank" rel="noopener noreferrer" className="underline hover:text-orange-300">Mistral AI Terms</a></li>
                <li><a href="https://www.zhipuai.cn/en/devdocs/privacy" target="_blank" rel="noopener noreferrer" className="underline hover:text-orange-300">ZhipuAI Privacy Policy</a></li>
              </ul>
              <p>
                <span className="text-indigo-400 font-bold">[7.3]</span> Do not input 
                sensitive, confidential, or personally identifiable information.
              </p>
            </div>
          </section>

          {/* Footer */}
          <div className="mt-12 pt-8 border-t border-[#2A2A2A]">
            <div className="space-y-4 text-gray-400 text-xs">
              <p>
                <span className="text-white font-bold">Last Updated:</span> {new Date().toLocaleDateString('en-US', { 
                  year: 'numeric', 
                  month: 'long', 
                  day: 'numeric' 
                })}
              </p>
              <p>
                <span className="text-white font-bold">Version:</span> 1.0.0
              </p>
              <p>
                <span className="text-white font-bold">Contact:</span> For questions about this 
                disclaimer, please contact the developer via{' '}
                <a 
                  href="https://linkedin.com/in/tanmay-kalbande" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-orange-400 underline hover:text-orange-300"
                >
                  LinkedIn
                </a>
              </p>
              <p className="text-yellow-400 font-semibold">
                ⚠️ By using Pustakam Injin, you acknowledge that you have read, understood, 
                and agree to be bound by this disclaimer.
              </p>
            </div>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="p-6 border-t border-[#2A2A2A] bg-[#141414]">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2 text-sm text-gray-400">
              <Info className="w-4 h-4" />
              <span>This disclaimer is also included in all PDF exports</span>
            </div>
            <button
              onClick={onClose}
              className="px-6 py-2.5 bg-white text-black rounded-lg font-semibold hover:bg-gray-200 transition-colors"
            >
              I Understand
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
